### ISSUE TITLE
Recommended node.js json-rpc library

### ISSUE THREAD

**Issue by Symbolics** [cxxxr/jsonrpc#28]
Has anyone got a recommendation for a JSON-RPC library for node.js that is known to work with jsonrpc? I've tried with [jayson ](https://github.com/tedeh/jayson) and the 'add' example works with the jayson CLI app, but not with jsonrpc (jsonrpc works with itself). Looking at the traffic with Fiddler, it seems as if the headers may be the problem. Here's the header from jayson's cli
```
POST / HTTP/1.1
Content-Length: 91
Content-Type: application/json; charset=utf-8
Accept: application/json
Host: 127.0.0.1:3000
Connection: close
```
and the one from jsonrpc is simply `  HTTP/1.1`. The response to jsonrpc is:
```
[Fiddler] Request Header parsing failed. Request was:
43 6F 6E 74 65 6E 74 2D 4C 65 6E 67 74 68 3A 20 36 39 0D 0A 0D 0A 7B 22  Content-Length: 69....{"
6A 73 6F 6E 72 70 63 22 3A 22 32 2E 30 22 2C 22 6D 65 74 68 6F 64 22 3A  jsonrpc":"2.0","method":
22 61 64 64 22 2C 22 70 61 72 61 6D 73 22 3A 5B 31 30 2C 32 30 5D 2C 22  "add","params":[10,20],"
69 64 22 3A 22 4F 69 38 4C 32 6F 7A 4B 59 71 72 54 22 7D                 id":"Oi8L2ozKYqrT"}     
```
It looks like we didn't get past the HTTP line. The[ jayson faq](https://github.com/tedeh/jayson#faq) seems to suggest that the problem may

> stem from the fact that JSON-RPC 2.0 specification is transport agnostic and these kind of behaviours are not defined by that specification

the behaviours he's referring to are newlines and other server protocol interactions. It would be great if jsonrpc had the ability to control such things, but in the interests of time I'd prefer to use something that is known to work.

Anyone have any ideas? What are they using in the Pocket Change application?

**Comment by cxxxr** [comment]
For example, in lem, vscode-jsonrpc is used.

https://github.com/lem-project/lem/blob/master/package.json
