### ISSUE TITLE
Support for jsonrpc 1.0

### ISSUE THREAD

**Issue by kilianmh** [cxxxr/jsonrpc#38]
I would like to use this library to access a jsonrpc but it is version 1.0. 
It looks like mainly `request-response.lisp` needs to be changed to get it working. 
Would you be interested to merge this feature if I do a PR for that? @cxxxr

**Comment by kilianmh** [comment]
For my usecase (Bitcoin Core RPC) it would be enough to **not** check the response for `"jsonrpc": "2.0"`.
Here would be some ideas how to achieve that

- This could be implemented either with a special-variable such as `*compatibility-mode*`, `*json-1-0-compatibility*`  or something similar. What name would you like? 

- Alternatively, or in combination with the special variable, we could introduce a `optional` / `keyword` parameter to `parse-message` and `parse-response`.

Which solution do you prefer?

**Comment by cxxxr** [comment]
Maybe either one is fine.

**Comment by kilianmh** [comment]
While implementing the compatibility with a special variable is certainly possible, another idea came to my mind:

What if we add a `slot` such as `rpc-version` to the `client` class (with `:initform 2.0`) Then we can optionally supply the rpc version in the `make-instance` method for the client. Accordingly the reqest/response validation is done for the specific rpc verson. Do you like the idea?

**Comment by cxxxr** [comment]
Indeed, that method may make more sense.

**Comment by kilianmh** [comment]
Thank you @cxxxr for merging #41 !
